### ISSUE TITLE
Website is unusable on mobile

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/ctlstore#3]
This looks like an interesting project. I tried to check out the website in order to learn more. Unfortunately the website doesn't play well with smaller viewports. See screenshot below.

![Screenshot of websiteon mobile](https://user-images.githubusercontent.com/571265/61338719-c59b3a00-a808-11e9-9ad5-23812284286c.jpg)

I don't know if this is a major concern for the project, but I figured I'd let you know either way :smile:

**Comment by collinvandyck** [comment]
Hey @stephenmathieson thanks for checking out ctlstore and reporting the issue!  Improving the mobile web experience is definitely on our radar.  Will leave this issue open to track it.

**Comment by collinvandyck** [comment]
We're going to soon be focusing on improving the project documentation and onboarding experience for ctlstore.  We've taken down the site for now, with the intent that a more comprehensive approach will follow. Because the site has been removed, I'm going to close this issue, but we will keep this front of mind. Thanks :)
